[workspace]
members = [
    "aya-cpu",
    "aya-dbg",
    "aya-game",
    "aya-parser",
    "aya-compiler",
]
default-members = ["aya-game", "aya-dbg"]
resolver = "2"

[workspace.dependencies]
aya-cpu = { path = "aya-cpu" }
aya-game = { path = "aya-game" }
aya-parser = { path = "aya-parser" }
aya-compiler = { path = "aya-compiler" }
