[workspace]
members = [
    "aya-core",
    "aya-frontend",
    "aya-parser",
    "aya-compiler",
    "aya-debugger",
]
default-members = ["aya-frontend", "aya-debugger"]
resolver = "2"

[workspace.dependencies]
aya-core = { path = "./aya-core" }
aya-parser = { path = "./aya-parser" }
aya-compiler = { path = "./aya-compiler" }
