[package]
name = "aya-dbg"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-game.workspace = true
aya-compiler.workspace = true
aya-cpu.workspace = true
iced = "0.13.1"

[[bin]]
name = "ayadbg"
path = "./src/main.rs"
