[package]
name = "aya-debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-console.workspace = true
aya-assembly.workspace = true
aya-cpu.workspace = true
iced = { version = "0.13.1", features = ["webgl"] }

[[bin]]
name = "ayadbg"
path = "./src/main.rs"
