mod add;
mod and;
mod call;
mod dec;
mod hlt;
mod inc;
mod jeq;
mod jge;
mod jgt;
mod jle;
mod jlt;
mod jmp;
mod jne;
mod lsh;
mod mov;
mod mul;
mod not;
mod or;
mod pop;
mod psh;
mod ret;
mod rsh;
mod sub;
mod xor;

pub use add::parse_add;
pub use and::parse_and;
pub use call::parse_call;
pub use dec::parse_dec;
pub use hlt::parse_hlt;
pub use inc::parse_inc;
pub use jeq::parse_jeq;
pub use jge::parse_jge;
pub use jgt::parse_jgt;
pub use jle::parse_jle;
pub use jlt::parse_jlt;
pub use jmp::parse_jmp;
pub use jne::parse_jne;
pub use lsh::parse_lsh;
pub use mov::parse_mov;
pub use mul::parse_mul;
pub use not::parse_not;
pub use or::parse_or;
pub use pop::parse_pop;
pub use psh::parse_psh;
pub use ret::parse_ret;
pub use rsh::parse_rsh;
pub use sub::parse_sub;
pub use xor::parse_xor;
